import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import myself from "../public/myselfRedBackground.png"
import code from "../public/code.png";
import WordPress from "../public/wordpress.png"
import consulting from "../public/consulting.png";
import Image from "next/image";
import projectDTS from "../public/DTS.png"
import projectFCAM from "../public/FCAM.png"
import project1 from "../public/AldeaGlobal.PNG"
import project2 from "../public/gaggalliance.PNG"
import project3 from "../public/ramac.PNG"
import project4 from "../public/hemco.PNG"


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Shawlorne's Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/homeIcon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl hover:animate-bounce">GearWestX</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl animate-bounce"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 hover:animate-pulse"
                  href="/SysEngineer2023.pdf"
                  target="_blank" 
            
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Shawlorne West
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl hover:animate-pulse">
               Systems Engineer | Front-End Developer | WordPress Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Web Developer JavaScript / PHP based with enough skills to provide services in both Front-End & Back-End
              , additionally have IT Support/Admin knowledge. 
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">

             <a 
             className="animate-bounce"
             href="https://twitter.com/WestShawlorne"
             target="_blank" >
             <AiFillTwitterCircle />
             </a>
              <a 
              className="animate-bounce"
              href="https://www.linkedin.com/in/shawlorne-west-297440228/"  
              target="_blank" >
              <AiFillLinkedin />
              </a>
              <a 
               className="animate-bounce"
               href="https://github.com/GearWestX"
               target="_blank" >
              <AiFillGithub />
              </a>
              
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative
                            overflow-hidden mt-20 md:h-96 md:w-96 scale-75">
              <Image 
              className="hover:animate"
              src={myself} layout="fill" objectFit="cover" 
              alt="Shawlorne West" 
              priority />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-4xl animate-bounce">My Services</h3>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my career as a Software Developer
              I've done tasks and  projects using different technologies
              and collaborated with talented people to support websites.
            </p>
            
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Mostly I've worked with back-end technologies such as:
              <span className="text-teal-500"> Java, C#, Node.JS, MySQL, PHP. </span>
              Nevetheless, you can find a very good use of my front-end skills
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image 
              className = "hover:animate-bounce" 
              src={WordPress} width={100} height={100} />
              <h3 className="text-4xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-2xl">
                Web Design / Front-End
              </h3>
              <p className="py-2">
                Developing pages from custom UX/UI designs to code into production.
              </p>
              <div className="hover:animate-pulse">
              <h4 className="py-4 text-teal-600">Skillset</h4>
              <p className="text-gray-800 py-1">WordPress</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">Next.JS</p>
              <p className="text-gray-800 py-1">TailWindCSS</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Sass</p>
              </div>

            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image 
              className = "hover:animate-bounce" 
              src={code} width={100} height={100} />
              <h3 className="text-4xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-2xl">
                Back-End
              </h3>
              <p className="py-2">
                Databases design / queries, algorithms OOP, MVC, API's.
              </p>
              <div className="hover:animate-pulse">
              <h4 className="py-4 text-teal-600">Skillset</h4>
              <p className="text-gray-800 py-1">Node.Js</p>
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">GraphQL</p>
              <p className="text-gray-800 py-1">Unix Commands</p>
              <p className="text-gray-800 py-1">C# with .NET/ EF</p>
              <p className="text-gray-800 py-1">Java with OOP</p>
              </div>



            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image 
              className = "hover:animate-bounce" 
              src={consulting} width={100} height={100} />
              <h3 className="text-4xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-2xl">IT Support / Admin / Consulting</h3>
              <p className="py-2">
                Google IT support certified and thanks to my degree
                I have excellent Software and Hardware troubleshooting skills.
              </p>
              <div className="hover:animate-pulse">
              <h4 className="py-4 text-teal-600">Skillset</h4>
              <p className="text-gray-800 py-1">Linux</p>
              <p className="text-gray-800 py-1">Networking</p>
              <p className="text-gray-800 py-1">CyberSecurity</p>
              <p className="text-gray-800 py-1">Virtualizations</p>
              <p className="text-gray-800 py-1">Cloud Support</p>
              </div>

            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-4xl animate-bounce">Portfolio</h3>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              So far I've worked side by side with Project Managers, Developers, UX/UI Designers, Team Leads 
              and collaborated in their repositories and websites.
            </p>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200">
             Below you can find some of the projects  
             where I've added new pages, sections,
             features, supported the back-end as a contributor.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-1 ">
              <a
              href="https://digitaltimesavers.com/"
              target="_blank">
               <Image
                className="rounded-lg object-scale-down hover:animate-pulse"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={projectDTS}
              />    
              </a>
             
            </div>

            <div className="basis-1/3 flex-1 ">
              <a
              href="https://fondocentroamericano.org/"
              target="_blank">
               <Image
                className="rounded-lg object-scale-down hover:animate-pulse"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={projectFCAM}
              />    
              </a>
             
            </div>
            
            <div className="basis-1/3 flex-1 ">
              <a
              href="https://aglobal.org.ni/"
              target="_blank">
               <Image
                className="rounded-lg object-scale-down hover:animate-pulse"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={project1}
              />    
              </a>
             
            </div>
            <div className="basis-1/3 flex-1">
              <a 
              href="https://gaggaalliance.org/"
              target="_blank">
              <Image
                className="rounded-lg object-scale-down hover:animate-pulse"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={project2}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
              href="https://www.ramac.com.ni/"
              target="_blank">
                <Image
                className="rounded-lg object-scale-down hover:animate-pulse"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={project3}
              />
              </a>
              
            </div>
            <div className="basis-1/3 flex-1">
            <a
              href="https://hemco.com.ni/"
              target="_blank">
              <Image
                className="rounded-lg object-scale-down hover:animate-pulse"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={project4}
              />
  
              </a>
              
             </div>
          </div>
        </section>
      </main>
    </div>
  );
}
